export const NOTIFICATION_FEATURE_UPGRADED = 'NOTIFICATION_FEATURE_UPGRADED';
export const NOTIFICATION_FEATURE_TECH_LEADER = 'NOTIFICATION_FEATURE_TECH_LEADER';
export const NOTIFICATION_MARKETS_INFLUENCE_INCREASED = 'NOTIFICATION_MARKETS_INFLUENCE_INCREASED';
export const NOTIFICATION_MARKETS_INFLUENCE_DECREASED = 'NOTIFICATION_MARKETS_INFLUENCE_DECREASED';
export const NOTIFICATION_PAYMENTS_UPGRADED = 'NOTIFICATION_PAYMENTS_UPGRADED';

export const NOTIFICATION_RENT_EXPIRED = 'NOTIFICATION_RENT_EXPIRED';
export const NOTIFICATION_COMPETITORS_ADD = 'NOTIFICATION_COMPETITORS_ADD';

// export const NOTIFICATION_MARKETS_INFLUENCE_DECREASED = 'NOTIFICATION_MARKETS_INFLUENCE_DECREASED';
