export const NOTIFICATION_FEATURE_UPGRADED = 'NOTIFICATION_FEATURE_UPGRADED';
export const NOTIFICATION_MARKETS_INFLUENCE_INCREASED = 'NOTIFICATION_MARKETS_INFLUENCE_INCREASED';
export const NOTIFICATION_MARKETS_INFLUENCE_DECREASED = 'NOTIFICATION_MARKETS_INFLUENCE_DECREASED';

// export const NOTIFICATION_MARKETS_INFLUENCE_DECREASED = 'NOTIFICATION_MARKETS_INFLUENCE_DECREASED';
