export const COMPANY_STYLE_FEATURE_ORIENTED = 'COMPANY_STYLE_FEATURE_ORIENTED';
export const COMPANY_STYLE_SEGMENT_ORIENTED = 'COMPANY_STYLE_SEGMENT_ORIENTED';
export const COMPANY_STYLE_BALANCED = 'COMPANY_STYLE_BALANCED';
