export const JOB_MOTIVATION_BUSINESS_OWNER = 'JOB_MOTIVATION_BUSINESS_OWNER';
export const JOB_MOTIVATION_IDEA_FAN = 'JOB_MOTIVATION_IDEA_FAN';
export const JOB_MOTIVATION_SALARY = 'JOB_MOTIVATION_SALARY';
export const JOB_MOTIVATION_PERCENTAGE = 'JOB_MOTIVATION_PERCENTAGE';


export const JOB_TASK_PROGRAMMER_POINTS = 'JOB_TASK_PROGRAMMER_POINTS';
export const JOB_TASK_MARKETING_POINTS = 'JOB_TASK_MARKETING_POINTS';

export const PROFESSION_PROGRAMMER = 'PROFESSION_PROGRAMMER';
export const PROFESSION_MARKETER = 'PROFESSION_MARKETER';
export const PROFESSION_DESIGNER = 'PROFESSION_DESIGNER';
export const PROFESSION_ANALYST = 'PROFESSION_ANALYST';

export const PRICE_OF_ONE_MP = 100;
export const PRICE_OF_ONE_PP = 100;
