export const TECHNICAL_DEBT_MODIFIER = 1.03;
export const TECHNOLOGY_COST_MODIFIER = 1.045;
export const SUPPORT_COST_MODIFIER = 1.08; // 0.65;


export const PROGRAMMER_EFFICIENCY_INTERN = 1;
export const PROGRAMMER_EFFICIENCY_JUNIOR = 3;
export const PROGRAMMER_EFFICIENCY_MIDDLE = 6;
export const PROGRAMMER_EFFICIENCY_SENIOR = 8;

export const PROGRAMMER_SALARY_INTERN = 1;
export const PROGRAMMER_SALARY_JUNIOR = 3;
export const PROGRAMMER_SALARY_MIDDLE = 5;
export const PROGRAMMER_SALARY_SENIOR = 8;

export const PROGRAMMER_CODE_QUALITY_INTERN = -8;
export const PROGRAMMER_CODE_QUALITY_JUNIOR = -3;
export const PROGRAMMER_CODE_QUALITY_MIDDLE = 1;
export const PROGRAMMER_CODE_QUALITY_SENIOR = 5;

export const SPAM_LOYALTY_IMPACT = 0.2;

export const DURATION_CORE_EXPLORATION = 100;
export const DURATION_TEMPORARY_BONUS = 100;
export const DURATION_CHANNEL_EXPLORATION = 15;


