export const JOB_MOTIVATION_BUSINESS_OWNER = 'JOB_MOTIVATION_BUSINESS_OWNER';
export const JOB_MOTIVATION_IDEA_FAN = 'JOB_MOTIVATION_IDEA_FAN';
export const JOB_MOTIVATION_SALARY = 'JOB_MOTIVATION_SALARY';
export const JOB_MOTIVATION_PERCENTAGE = 'JOB_MOTIVATION_PERCENTAGE';


export const JOB_TASK_PROGRAMMER_POINTS = 'JOB_TASK_PROGRAMMER_POINTS';
export const JOB_TASK_MARKETING_POINTS = 'JOB_TASK_MARKETING_POINTS';
