export const PLAYER_ACTIONS_INCREASE_MONEY = 'PLAYER_ACTIONS_INCREASE_MONEY';
export const PLAYER_ACTIONS_IMPROVE_SKILL = 'PLAYER_ACTIONS_IMPROVE_SKILL';
export const PLAYER_ACTIONS_EXPENSES_ADD = 'PLAYER_ACTIONS_EXPENSES_ADD';
export const PLAYER_ACTIONS_EXPENSES_REMOVE = 'PLAYER_ACTIONS_EXPENSES_REMOVE';
export const PLAYER_ACTIONS_LOANS_TAKE = 'PLAYER_ACTIONS_LOANS_TAKE';
export const PLAYER_ACTIONS_LOANS_REPAY = 'PLAYER_ACTIONS_LOANS_REPAY';
