export const WORLD_UPGRADE = 'WORLD_UPGRADE';


export const ACTIONS_UPGRADE_CORE = 'ACTIONS_UPGRADE_CORE';
export const ACTIONS_EXPLORE_CORE = 'ACTIONS_EXPLORE_CORE';

export const ACTIONS_UPGRADE_OFFER = 'ACTIONS_UPGRADE_OFFER';
export const ACTIONS_EXPLORE_OFFER = 'ACTIONS_EXPLORE_OFFER';
